import turtle as trtl
painter=trtl.Turtle()
x=input("what color do you want your circle to be?")
painter.color(x)

painter.circle(100)

y=input("what color do you want your square to be?")
painter.color(y)
painter.forward(100)
painter.left(90)
painter.forward(200)
painter.left(90)
painter.forward(200)
painter.left(90)
painter.forward(200)
painter.left(90)
painter.forward(100)
z=input("what color do you want your triangle to be?")
painter.color(z)
painter.left(64)
painter.forward(215)
painter.left(116.5)
painter.forward(192)
painter.left(116.5)
painter.forward(215)
wn = trtl.Screen()
wn.mainloop()